version: '3'
services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    restart: always
    env_file: .env
    ports:
      -  3306:3306
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - web
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    restart: always 
    env_file: .env
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    volumes:
      - wordpressfile:/var/www/html
    networks:
      - web
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    image: nginx
    ports:
        - 443:443
    depends_on:
      - wordpress
    volumes:
      - wordpressfile:/var/www/html
    networks:
      - web

volumes:
  mariadb:
  wordpressfile:

networks:
  web:
    driver: bridge 
