version: '3'
services:
    # bonus
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    depends_on:
      - wordpress
    ports:
     - 6379:6379
    restart: always
    env_file:
      - .env
    volumes:
      - wordpressfiles:/var/www/html
    networks:
      - web
  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    volumes:
      - "wordpressfiles:/var/www/html"
    env_file:
      - .env
    depends_on:
        - wordpress
    ports:
      - 21:21
      - "21100-21110:21100-21110"
    networks:
      - web
    restart: always


    #mandatory
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    restart: always
    env_file: 
      - .env
    ports:
      -  3306:3306
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - web
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    restart: always 
    env_file: 
      - .env
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    volumes:
      - wordpressfiles:/var/www/html
    networks:
      - web
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    image: nginx
    ports:
        - 443:443
    depends_on:
      - wordpress
    volumes:
      - wordpressfiles:/var/www/html
    networks:
      - web

volumes:
  mariadb:
    # driver: local
    # driver_opts:
    #   type: none
    #   device: /home/yakhoudr/data/wordpress
    #   o: bind
  wordpressfiles:

networks:
  web:
    driver: bridge 
