baseURL = "https://localhost/static"
theme = "nightfall"
paginate = 8
canonifyURLs = true

[params]
 
 [Params.Terminal]
  schema = "gruvbox_dark"

 userName = "eelhafia"
 pcName = "debian:11"
 workDir = "a"
 
 description = """
 Hi...
 I Am essadike
 This is My Portfolio!
 
 """
 
 [Params.Tree]
 use = true
 files = [
 ["Python", "https://python.org/"],
 ["Django", ""],
 ["Hugo", "https://gohugo.io/"],
 ["Docker", ""],
 
 ]