baseURL = "https://eelhafia.42.fr/hugo"
title = 'service bonus docker'
languageCode = "de"
defaultContentLanguage = "de"
paginate = "7"
theme = "spectral"

[params]
fancytitle = '<img height="128" src="/images/logo.svg" alt="Logo"/><br />essadike'
copyright = "essadike elhafiane"
startbuttonLink = "#contact"

[params.social]
instagram = "essadike_elhafiane"
facebook = "saddik.elhafiane"
github = "essadike-elhafiane"

