baseURL = "https://eelhafia.42.fr/hugo"
theme = "shell"
paginate = 8
canonifyURLs = true

[params]
 
    [Params.Terminal]
    schema = "gruvbox_dark"

    userName = "eelhafia"
    pcName = "debian:11"
    workDir = "/var/hugo/info"

    description = """
    Hi...
    I Am essadike!

    """
[Params.Tree]
    use = true
    files = [
        ["Hugo", "https://gohugo.io/"],
        ["staticWebsite", "https://localhost/static"],
    ]